version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2  # Use CircleCI OpenJDK 15 image
    working_directory: ~/repo

    steps:
      - checkout

      # Install necessary tools like Maven, wget, curl
      - run:
          name: Install Required Tools
          command: |
            sudo apt-get update
            #sudo apt-get install -y maven wget curl

      # Verify the installation of Java
      - run:
          name: Verify Java Installation
          command: java -version

      # Build the application using Maven
      - run:
          name: Build the Application
          command: mvn clean package

      # Install and configure Tomcat
      - run:
          name: Install Tomcat
          command: |
            wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.30/bin/apache-tomcat-10.1.30.tar.gz
            tar xzf apache-tomcat-10.1.30.tar.gz
            mv apache-tomcat-10.1.30 ~/tomcat
            rm apache-tomcat-10.1.30.tar.gz
            chmod +x ~/tomcat/bin/*.sh

      # Deploy the WAR file to Tomcat
      - run:
          name: Deploy to Tomcat
          command: |
            cp target/*.war ~/tomcat/webapps/

      # Start Tomcat
      - run:
          name: Start Tomcat Server
          command: |
            ~/tomcat/bin/startup.sh
            sleep 60  # Wait for Tomcat to start

      # Extract the port number from server.xml (defaults to 8080)
      - run:
          name: Extract Tomcat Port
          command: |
            export TOMCAT_PORT=$(grep -oP 'port="\K\d+' ~/tomcat/conf/server.xml | head -1)
            echo "Tomcat is running on port: $TOMCAT_PORT"
            echo $TOMCAT_PORT > tomcat_port.txt  # Save to file for later use

      # Verify Tomcat is running and curl the port dynamically
      - run:
          name: Capture Tomcat Status
          command: |
            export TOMCAT_PORT=$(cat tomcat_port.txt)
            netstat -tuln | grep $TOMCAT_PORT || echo "Port $TOMCAT_PORT not found"
            curl -I http://localhost:$TOMCAT_PORT > tomcat_status.txt || echo "Tomcat not started on port $TOMCAT_PORT."
            cat tomcat_status.txt  # Print the status to CircleCI output

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
