version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2  # Use CircleCI OpenJDK 15 image
    working_directory: ~/repo

    steps:
      - checkout

      # Install necessary tools like Maven, wget, curl
      - run:
          name: Install Required Tools
          command: |
            sudo apt-get update
            #sudo apt-get install -y maven wget curl

      # Verify the installation of Java
      - run:
          name: Verify Java Installation
          command: java -version

      # Build the application using Maven
      - run:
          name: Build the Application
          command: mvn clean package

      - run:
          name: Upload WAR to JFrog Artifactory
          command: |
            curl -X PUT "https://demojfrog1.jfrog.io/artifactory/tomcatapp/myapp.war" \
            -H "X-JFrog-Art-Api: ${JFROG_TOKEN}" \
            -H "Content-Type: application/java-archive" \
            --data-binary @target/myapp.war

  deploy:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - run:
          name: Install Tomcat
          command: |
            sudo apt-get update
            sudo apt-get install -y tomcat9
      - run:
          name: Start Tomcat
          command: sudo systemctl start tomcat9
      - run:
          name: Deploy WAR file to Tomcat
          command: |
            sudo cp target/your-app.war /opt/tomcat/webapps/
      - run:
          name: Wait for Tomcat to start
          command: sleep 60
      - run:
          name: Check Tomcat Status
          command: |
            if systemctl status tomcat9; then
              echo "Tomcat is running"
            else
              echo "Tomcat is not running"
              exit 1
            fi
      - run:
          name: Test Application
          command: |
            curl -f http://localhost:8080/your-app || (echo "App is not responding" && exit 1)

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
