version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:15  # Use CircleCI OpenJDK 15 image
    working_directory: ~/repo

    steps:
      - checkout

      # Install necessary tools like Maven, wget, curl
      - run:
          name: Install Required Tools
          command: |
            sudo apt-get update
            #sudo apt-get install -y maven wget curl
      
      # Verify the installation of Java
      - run:
          name: Verify Java Installation
          command: java -version
      
      # Build the application using Maven
      - run:
          name: Build the Application
          command: mvn clean package
      
      # Install and configure Tomcat
      - run:
          name: Install Tomcat
          command: |
            wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.30/bin/apache-tomcat-10.1.30.tar.gz
            tar xzf apache-tomcat-10.1.30.tar.gz
            mv apache-tomcat-10.1.30 ~/tomcat
            rm apache-tomcat-10.1.30.tar.gz
            chmod +x ~/tomcat/bin/*.sh
      
      # Deploy the WAR file to Tomcat (assuming the .war file is created during the build process)
      - run:
          name: Deploy to Tomcat
          command: |
            cp target/*.war ~/tomcat/webapps/
      
      # Start Tomcat
      - run:
          name: Start Tomcat Server
          command: |
            ~/tomcat/bin/startup.sh
            sleep 10  # Wait for Tomcat to start
            curl -I http://localhost:8080

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
