version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:17.0  # Use OpenJDK 17 image based on CircleCI

jobs:
  build_and_push:
    executor: docker-executor
    environment:
      DOCKER_IMAGE: tomcat:8.0                                        # Name of the Docker image
      DOCKER_REPO: ${DOCKER_REPO}                                     # Repository name in JFrog
      DOCKER_TAG: ${CIRCLE_BUILD_NUM}                                 # Tag based on CircleCI build number
      JFROG_BASE_URL: ${JFROG_BASE_URL}                               # JFrog base URL
      JFROG_USERNAME: ${JFROG_USERNAME}                               # JFrog username
      JFROG_API_TOKEN: ${JFROG_API_TOKEN}                             # Your actual API token
      CIRCLE_BUILD_NUM: ${CIRCLE_BUILD_NUM}                           # Automatically provided by CircleCI

    steps:
      - checkout

      - run:
          name: Install Docker
          command: |
            echo "Updating package list..."
            sudo apt-get update
            
            # Install prerequisites
            echo "Installing prerequisites..."
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

            # Add Docker's official GPG key
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

            # Set up the stable repository for Ubuntu
            echo "Setting up Docker repository for Ubuntu..."
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            # Update the package index again
            echo "Updating package index..."
            sudo apt-get update

            # Install the latest version of Docker
            echo "Installing the latest version of Docker..."
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

            # Verify Docker installation
            echo "Verifying Docker installation..."
            docker --version

      - run:
          name: Start Docker Daemon
          command: |
            sudo systemctl start docker

      - run:
          name: Verify Docker Daemon
          command: |
            sudo systemctl status docker || echo "Docker is not running"

      - run:
          name: Build the Maven Project
          command: mvn clean package  # Adjust based on your actual build command

      - run:
          name: Build Docker Image
          command: docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .

      - run:
          name: Tag Docker Image
          command: |
            echo "Tagging Docker image..."
            docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${JFROG_BASE_URL}/${DOCKER_REPO}/${DOCKER_IMAGE}:${DOCKER_TAG}

      - run:
          name: Push Docker Image to JFrog
          command: |
            echo "Pushing Docker image to JFrog Artifactory..."
            docker push ${JFROG_BASE_URL}/${DOCKER_REPO}/${DOCKER_IMAGE}:${DOCKER_TAG}

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push
