version: 2.1

executors:
  build-executor:
    docker:
      - image: cimg/openjdk:15.0  # Image for building

  publish-executor:
    docker:
      - image: tomcat:9.0          # Image for publishing

jobs:
  build:
    executor: build-executor
    steps:
      - checkout

      - run:
          name: Build Custom Docker Image with Tomcat
          command: |
            echo "Building custom Docker image with Tomcat..."
            DOCKER_IMAGE_NAME="java-tomcat-sample"  # Name of the image you want to tag
            DOCKER_TAG="latest"                      # Tag for the image
            IMAGE_TAG="${DOCKER_IMAGE_NAME}:${DOCKER_TAG}"  # Tag for the local image
            echo "Final Docker image tag: ${IMAGE_TAG}"

            # Build the Docker image using the Dockerfile
            docker build -t "${IMAGE_TAG}" .

      - run:
          name: List Docker Images
          command: |
            echo "Listing Docker images to verify build..."
            docker images

  publish:
    executor: publish-executor
    steps:
      - run:
          name: Deploy Application to Tomcat
          command: |
            echo "Deploying application to Tomcat..."
            DOCKER_IMAGE_NAME="java-tomcat-sample"  # Ensure this matches the built image name
            docker run -d -p 8090:8080 "${DOCKER_IMAGE_NAME}"

workflows:
  version: 2
  build_and_publish_workflow:
    jobs:
      - build
      - publish:
          requires:
            - build
