version: 2.1

executors:
  test-executor:
    docker:
      - image: circleci/docker:20.10.7  # Base image to test

jobs:
  test_image:
    executor: test-executor
    steps:
      - checkout
      - run:
          name: Verify Installed Tools
          command: |
            echo "Checking Docker image and installed tools..."
            
            # Check Docker version
            echo "Checking Docker..."
            if command -v docker &> /dev/null
            then
                echo "Docker is installed."
                docker --version
            else
                echo "Docker is not installed."
            fi

            # Check Java version (OpenJDK)
            echo "Checking OpenJDK..."
            if command -v java &> /dev/null
            then
                echo "OpenJDK is installed."
                java -version
            else
                echo "OpenJDK is not installed."
            fi

            # Check Maven
            echo "Checking Maven..."
            if command -v mvn &> /dev/null
            then
                echo "Maven is installed."
                mvn -v
            else
                echo "Maven is not installed."
            fi

            # Check Git
            echo "Checking Git..."
            if command -v git &> /dev/null
            then
                echo "Git is installed."
                git --version
            else
                echo "Git is not installed."
            fi

workflows:
  version: 2
  test_workflow:
    jobs:
      - test_image
