version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:15.0

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Check for Docker
          command: docker --version || { echo "Docker is not installed"; exit 1; }

      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Application
          command: mvn -f pom.xml clean package

      - run:
          name: Build Docker Image
          command: |
            docker build -t githbgk/tomcat:your-tag-name .

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER" --password-stdin

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push githbgk/tomcat:your-tag-name

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
