version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:15.0  # Use CircleCI's base image with OpenJDK
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Check out the code from your repo

      # Build the application using Maven
      - run:
          name: Build Application
          command: mvn clean package  # Adjust according to your Maven configuration

      # Archive the WAR artifacts
      - run:
          name: Archive Artifacts
          command: |
            mkdir -p artifacts  # Create an artifacts directory
            cp target/*.war artifacts/  # Copy WAR files to the artifacts directory

      # Create Docker Image for Tomcat
      - run:
          name: Create Tomcat Docker Image
          command: |
            docker build -t tomcatsamplewebapp:${CIRCLE_BUILD_NUM} .  # Use CircleCI build number as tag

      # Optional: Push Docker Image to a Registry
      - run:
          name: Push Docker Image
          command: |
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin  # Log in to Docker registry
            docker push tomcatsamplewebapp:${CIRCLE_BUILD_NUM}  # Push the Docker image

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
