version: 2.1

executors:
  test-executor:
    docker:
      - image: cimg/openjdk:15.0  # Image for building
      - image: tomcat:9.0          # Base image for publishing

jobs:
  build_and_push:
    executor: test-executor
    steps:
      - checkout

      # Build Docker Image
      - run:
          name: Build Docker Image
          command: |
            echo "Building Docker image..."
            IMAGE_NAME="java-tomcat-sample"  # Name of the image
            DOCKER_TAG="latest"  # Tag for the image
            IMAGE_TAG="${IMAGE_NAME}:${DOCKER_TAG}"  # Tag for the local image
            echo "Final Docker image tag: ${IMAGE_TAG}"

            # Build the Docker image using the Dockerfile
            docker build -t "${IMAGE_TAG}" .

      - run:
          name: List Docker Images
          command: |
            echo "Listing Docker images to verify build..."
            docker images

      # Uncomment below if you wish to push the image to JFrog
      # - run:
      #     name: Push Docker Image to JFrog
      #     command: |
      #       echo "Pushing Docker image to JFrog Artifactory..."
      #       echo "Logging into JFrog..."
      #       echo "${JFROG_API_TOKEN}" | docker login ${JFROG_BASE_URL} -u "${JFROG_USERNAME}" --password-stdin
      #
      #       docker push "${IMAGE_TAG}"

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push
