version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2  # Use CircleCI OpenJDK 15 image
    working_directory: ~/repo

    steps:
      - checkout

      # Install necessary tools like Maven, wget, curl
      - run:
          name: Install Required Tools
          command: |
            sudo apt-get update
            #sudo apt-get install -y maven wget curl

      # Verify the installation of Java
      - run:
          name: Verify Java Installation
          command: java -version

      # Build the application using Maven
      - run:
          name: Build the Application
          command: mvn clean package

      # Install and configure Tomcat
      - run:
          name: Install Tomcat
          command: |
            wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.30/bin/apache-tomcat-10.1.30.tar.gz
            tar xzf apache-tomcat-10.1.30.tar.gz
            mv apache-tomcat-10.1.30 ~/tomcat
            rm apache-tomcat-10.1.30.tar.gz
            chmod +x ~/tomcat/bin/*.sh

      # Deploy the WAR file to Tomcat
      - run:
          name: Deploy to Tomcat
          command: |
            cp target/*.war ~/tomcat/webapps/

      # Start Tomcat
      - run:
          name: Start Tomcat Server
          command: |
            ~/tomcat/bin/startup.sh
            sleep 60  # Wait for Tomcat to start

      # Extract the port number from server.xml (defaults to 8080)
      - run:
          name: Extract Tomcat Port
          command: |
            export TOMCAT_PORT=$(grep -oP 'port="\K\d+' ~/tomcat/conf/server.xml | head -1)
            echo "Tomcat is configured to run on port: $TOMCAT_PORT"
            echo $TOMCAT_PORT > tomcat_port.txt  # Save to file for later use

      # Verify if Tomcat is running
      - run:
          name: Check if Tomcat is Running
          command: |
            if ps -ef | grep '[t]omcat'; then
              echo "Tomcat is running"
            else
              echo "Tomcat is not running" && exit 1
            fi

      # Check if Tomcat is listening on the captured port
      - run:
          name: Check if Tomcat is Listening on Port
          command: |
            export TOMCAT_PORT=$(cat tomcat_port.txt)
            if netstat -tuln | grep ":$TOMCAT_PORT"; then
              echo "Tomcat is listening on port $TOMCAT_PORT"
            else
              echo "Tomcat is not listening on port $TOMCAT_PORT" && exit 1
            fi

      # Verify Tomcat is accessible via curl
      - run:
          name: Verify Tomcat Access
          command: |
            export TOMCAT_PORT=$(cat tomcat_port.txt)
            curl -I http://localhost:$TOMCAT_PORT || echo "Failed to connect to Tomcat on port $TOMCAT_PORT."

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
