version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:15.0  # CircleCI's OpenJDK image

jobs:
  build_and_push:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            echo "Building Docker image..."
            docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .

      - run:
          name: Tag Docker Image
          command: |
            echo "Tagging Docker image..."
            docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${JFROG_BASE_URL}/${DOCKER_REPO}/${DOCKER_IMAGE}:${DOCKER_TAG}

      - run:
          name: Push Docker Image to JFrog
          command: |
            echo "Pushing Docker image to JFrog Artifactory..."
            docker push ${JFROG_BASE_URL}/${DOCKER_REPO}/${DOCKER_IMAGE}:${DOCKER_TAG}

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push
