version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker:
          #version: 2.24.5  # Specify the Docker version you want to use
          docker_layer_caching: true  # Optional: speeds up builds by caching layers
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER" --password-stdin
      - run:
          name: Pull Image
          command: docker pull cimg/base:2022.09
      - run:
          name: Tag Image
          command: docker tag cimg/base:2022.09 your-dockerhub-username/your-image-name:latest
      - run:
          name: Push Image to Docker Hub
          command: docker push your-dockerhub-username/your-image-name:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
